<a href="https://colab.research.google.com/github/lakshit2808/Kaggle-Competitions/blob/master/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
train_df = pd.read_csv("train.csv")
train_df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
train_df.head()
X_df = train_df[['Pclass', 'Sex','Age','SibSp','Parch','Fare','Embarked','Survived']]
X_df.head(3)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived
0       3    male  22.0      1      0   7.2500        S         0
1       1  female  38.0      1      0  71.2833        C         1
2       3  female  26.0      0      0   7.9250        S         1

In [ ]:
X_df.isnull().sum()
X_df.shape

(891, 8)

In [ ]:
X = X_df.iloc[:,:].values
X

array([[3, 'male', 22.0, ..., 7.25, 'S', 0],
       [1, 'female', 38.0, ..., 71.2833, 'C', 1],
       [3, 'female', 26.0, ..., 7.925, 'S', 1],
       ...,
       [3, 'female', nan, ..., 23.45, 'S', 0],
       [1, 'male', 26.0, ..., 30.0, 'C', 1],
       [3, 'male', 32.0, ..., 7.75, 'Q', 0]], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,2:3])
X[:,2:3] = imputer.transform(X[:,2:3])

In [ ]:
df_em_miss = pd.DataFrame(X)

In [ ]:
df_em_miss.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    2
7    0
dtype: int64

In [ ]:
new_df =df_em_miss.dropna()

In [ ]:
new_df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [ ]:
new_df.head(3)

0       1   2  3  4        5  6  7
0  3    male  22  1  0     7.25  S  0
1  1  female  38  1  0  71.2833  C  1
2  3  female  26  0  0    7.925  S  1

In [ ]:
X = new_df.values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [6])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
X_train = X[:,:-1]
Y_train = X[:,-1]
Y_train=Y_train.astype('int')

## Training the model

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0,solver='lbfgs',max_iter=10000)
classifier.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Test

In [ ]:
test_df = pd.read_csv("test.csv")
X_df = test_df[['PassengerId','Pclass', 'Sex','Age','SibSp','Parch','Fare','Embarked']]
X_df.head(3)

PassengerId  Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0          892       3    male  34.5      0      0  7.8292        Q
1          893       3  female  47.0      1      0  7.0000        S
2          894       2    male  62.0      0      0  9.6875        Q

In [ ]:
X_df.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
dtype: int64

In [ ]:
X_test = X_df.iloc[:,1:].values
X_test

array([[3, 'male', 34.5, ..., 0, 7.8292, 'Q'],
       [3, 'female', 47.0, ..., 0, 7.0, 'S'],
       [2, 'male', 62.0, ..., 0, 9.6875, 'Q'],
       ...,
       [3, 'male', 38.5, ..., 0, 7.25, 'S'],
       [3, 'male', nan, ..., 0, 8.05, 'S'],
       [3, 'male', nan, ..., 1, 22.3583, 'C']], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_test[:,2:3])
X_test[:,2:3] = imputer.transform(X_test[:,2:3])

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_test[:,5:6])
X_test[:,5:6] = imputer.transform(X_test[:,5:6])

In [ ]:
df_test = pd.DataFrame(X_test)
df_test.isnull().sum()
df_test.head(3)

0       1     2  3  4       5  6
0  3    male  34.5  0  0  7.8292  Q
1  3  female    47  1  0       7  S
2  2    male    62  0  0  9.6875  Q

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_test[:,1] = le.fit_transform(X_test[:,1])

In [ ]:
X_test

array([[3, 1, 34.5, ..., 0, 7.8292, 'Q'],
       [3, 0, 47.0, ..., 0, 7.0, 'S'],
       [2, 1, 62.0, ..., 0, 9.6875, 'Q'],
       ...,
       [3, 1, 38.5, ..., 0, 7.25, 'S'],
       [3, 1, 30.272590361445783, ..., 0, 8.05, 'S'],
       [3, 1, 30.272590361445783, ..., 1, 22.3583, 'C']], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [6])], remainder = 'passthrough')
X_test = np.array(ct.fit_transform(X_test))

In [ ]:
X_test

array([[0.0, 1.0, 0.0, ..., 0, 0, 7.8292],
       [0.0, 0.0, 1.0, ..., 1, 0, 7.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 9.6875],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 0, 7.25],
       [0.0, 0.0, 1.0, ..., 0, 0, 8.05],
       [1.0, 0.0, 0.0, ..., 1, 1, 22.3583]], dtype=object)

In [ ]:
y_ = classifier.predict(X_test)

In [ ]:
pas_id = X_df['PassengerId']

In [ ]:
submission = {'PassengerId': pas_id, 'Survived': y_} 
submission = pd.DataFrame(submission)
submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         1
4          896         0

In [ ]:
submission.to_csv('submission.csv', index = False)